export type GamePhase =
  | "LOBBY"
  | "WRITING"
  | "VOTING"
  | "ROUND_RESULTS"
  | "FINAL_RESULTS";

export interface GameSettings {
  totalRounds: number;
  writingDurationSec: number;
  votingDurationSec: number;
  minPlayers: number;
  maxPlayers: number;
}

export interface PlayerState {
  id: string;
  name: string;
  score: number;
  isHost: boolean;
  connected: boolean;
  joinedAt: number;
}

export interface DefinitionOption {
  id: string;
  text: string;
}

export interface RoundState {
  roundNumber: number;
  totalRounds: number;
  word: string | null;
  options: DefinitionOption[];
  phaseStartedAt: number;
  phaseEndsAt: number | null;
  submittedCount: number;
  votedCount: number;
  hasSubmitted: boolean;
  hasVoted: boolean;
  votedOptionId: string | null;
  correctOptionId: string | null;
}

export interface RoomState {
  code: string;
  phase: GamePhase;
  hostId: string;
  players: PlayerState[];
  settings: GameSettings;
  round: RoundState | null;
  updatedAt: number;
}

export interface ApiSuccess<T> {
  ok: true;
  data: T;
}

export interface ApiError {
  ok: false;
  error: string;
}

export type ApiResponse<T> = ApiSuccess<T> | ApiError;

export interface SessionPayload {
  playerId: string;
  sessionToken: string;
}

export type OptionSource = "player" | "correct";

export interface InternalPlayer {
  id: string;
  sessionToken: string;
  name: string;
  score: number;
  joinedAt: number;
  connected: boolean;
}

export interface PlayerRoundDefinition {
  rawDefinition?: string;
  displayDefinition: string;
  isAutoGenerated: boolean;
}

export interface InternalDefinitionOption {
  id: string;
  text: string;
  source: OptionSource;
  ownerPlayerId: string | null;
}

export interface InternalRoundState {
  roundNumber: number;
  word: string;
  correctDefinition: string;
  correctOptionId: string;
  definitionsByPlayerId: Map<string, PlayerRoundDefinition>;
  options: InternalDefinitionOption[];
  votesByPlayerId: Map<string, string>;
  phaseStartedAt: number;
  phaseEndsAt: number | null;
}

export interface InternalRoom {
  code: string;
  hostId: string;
  players: Map<string, InternalPlayer>;
  phase: GamePhase;
  settings: GameSettings;
  round: InternalRoundState | null;
  roundTimeout: NodeJS.Timeout | null;
  currentRoundNumber: number;
  isFinalizingWriting: boolean;
  isFinalizingVoting: boolean;
  updatedAt: number;
}
